from os.path import join
from pathlib import Path

# Directories
PROJECT_DIRECTORY = Path(__file__).parents[1]
SRC_DIRECTORY = join(PROJECT_DIRECTORY, "src")
INPUT_DIRECTORY = join(PROJECT_DIRECTORY, "input")
RESULT_DIRECTORY = join(PROJECT_DIRECTORY, "results")

INPUT_DIRECTORY_UC1 = join(INPUT_DIRECTORY, "uc1")
INPUT_DIRECTORY_UC2 = join(INPUT_DIRECTORY, "uc2")

INPUT_DIRECTORY_UC1_GS = join(INPUT_DIRECTORY_UC1, "gs")
INPUT_DIRECTORY_UC1_ALGO = join(INPUT_DIRECTORY_UC1, "algo_output")
INPUT_DIRECTORY_UC2_GS = join(INPUT_DIRECTORY_UC2, "gs")
INPUT_DIRECTORY_UC2_ALGO = join(INPUT_DIRECTORY_UC2, "algo_output")